baseURL = "/"
title = "Park Players"
subtitle = "Detroit's oldest and longest-running community theatre"
languageCode = "en-us"
theme = "hugo-travelify-theme"
# DisqusShortname = ""
GoogleAnalytics = ""
canonifyURLs = true
metaDataFormat = "toml"

[params]
    author = "Aspire"
    site_description = "Park Players Detroit"
    copyright  = "Copyright"
    avatar = "css/images/avatar.png"
    logo = "/images/logo.png"
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "January 02, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = ["css"]
    custom_js  = ["js"]

[[menu.main]]
    name  = "Shows"
    url   = "/show/"
    weight = 10

[[menu.main]]
    name = "Announcements"
    url = "/announcement/"
    weight = 11

[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 12

[[menu.main]]
    name  = "Contact"
    url   = "/contact/"
    weight = 20

[social]
    # instagram       = "nikimonikado"
    # youtube         = "nikimonikado"
    facebook        = "ParkPlayersDetroit"
    # twitter         = "nikimonikado"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = false
    search = false
    mailchimp = false
    # mailchimpform = "//balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745"
    author = true
    facebook_like = false

[params.slider]
    enable = true
    num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.

[Taxonomies]
    tags = "tags"
    categories = "categories"
    author = "author"
