backend:
  name: git-gateway
  branch: master

media_folder: "static/images"

collections:
  - name: "announcement"
    label: "Announcement"
    folder: "content/announcement"
    create: true
  - name: "show"
    label: "Show"
    folder: "content/show"
    create: true

fields:
  - {label: "Title", name: "title"}
