backend:
  name: git-gateway
  branch: master

media_folder: "static/images"

collections:
  - name: "announcement"
    label: "Announcements"
    folder: "content/announcement"
    create: true

fields:
  - {label: "Title", name: "title"}
