backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "images"

publish_mode: editorial_workflow

collections:
  - name: "announcement"
    label: "Announcements"
    folder: "content/announcement"
    create: true
    fields:
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["announcement"] }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "show"
    label: "Shows"
    folder: "content/show"
    create: true
    fields:
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["show"] }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    fields:
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
