backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "images"

publish_mode: editorial_workflow

collections:
  - name: "announcement"
    label: "Announcement"
    folder: "content/announcement"
    create: true
    fields:
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "show"
    label: "Show"
    folder: "content/show"
    create: true
    fields:
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    fields:
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
