backend:
  name: git-gateway
  branch: master

media_folder: "static/images"

collections:
  - name: "announcement"
    label: "Announcement"
    folder: "content/announcement"
    create: true
  - name: "show"
    label: "Show"
    folder: "content/show"
    create: true
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
fields:
  - { label: "Title", name: "title" }
  - { label: "Publish Date", name: "date", widget: "datetime" }
  - { label: "Banner", name: "banner", widget: "image" }
  - { label: "Body", name: "body", widget: "markdown" }
